image: python:3.10-slim
stages:
  - lint
  - test
before_script:
  - python -m pip install --upgrade pip
  - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
check_code_format:
  stage: lint
  script:
    - pip install flake8
    - flake8 main.py

run_python_tests:
  stage: test
  script:
    - pip install pytest
    - pytest test_main.py
