image: python:3.10-slim
before_script:
  - python -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
  - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

stages:
  - lint
  - test

check_code_format:
  stage: lint
  script:
    # 此时 pip 已经默认使用清华源，无需重复指定
    - pip install flake8
    - flake8 main.py

run_python_tests:
  stage: test
  script:
    - pip install pytest
    - pytest test_main.py